### ISSUE TITLE
Page header contrinution link inside course pages is wrong

### ISSUE THREAD

**Issue by amirihusayn** [ceituut/ceituut.github.io#52]
The `getRepoName()` function inside `components/PageHeader.js` should get related repository name from `utils/course-nav-items.js`. But somehow it doesn't  work.

**Comment by akansjain** [comment]
Hey @amirihusayn ,
This seems like an easy bug. Please assign this issue to me.

**Comment by amirihusayn** [comment]
Thanks @akansjain ! I hope you do it well.
