### ISSUE TITLE
Use tabs for curriculum guide page

### ISSUE THREAD

**Issue by amirihusayn** [ceituut/ceituut.github.io#58]
Just like [bus-stop-times page](https://codegeeks.ir/requirements/bus-stop-times) We should add tabs using `Components/Tabs.js` to [curriculum-guide page](https://codegeeks.ir/requirements/curriculum-guide). So We'll see one semester courses at a time.

**Comment by kaleemullah786** [comment]
hey, can i work on it

**Comment by amirihusayn** [comment]
> hey, can i work on it

Sure ! I hope You do it well !

**Comment by amirihusayn** [comment]
That's very kind of You ! @kaleemullah786

**Comment by kaleemullah786** [comment]
> That's very kind of You! @kaleemullah786

@amirihusayn thanks agian! can you suggest some good projects to contribute, leading to job opportunities

**Comment by amirihusayn** [comment]
There are a lot of open source projects; But if I had enough time I would contribute on [drawio](https://github.com/jgraph/drawio) .

**Comment by kaleemullah786** [comment]
Great!

**Comment by kaleemullah786** [comment]
> There are a lot of open source projects; But if I had enough time I would contribute on [drawio](https://github.com/jgraph/drawio).

@amirihusayn any other suggestions

**Comment by amirihusayn** [comment]
I'm not sure. See what area You like, then search and find a repository that matches your favorites, abilities and time.

**Comment by kaleemullah786** [comment]
Right
