### ISSUE TITLE
Make file explorer responsive

### ISSUE THREAD

**Issue by amirihusayn** [ceituut/ceituut.github.io#59]
Update `Components/FileExplorer.js` styles to be more responsive specially on mobile devices.

**Comment by kaleemullah786** [comment]
hey can you assign it to me

**Comment by amirihusayn** [comment]
> hey can you assign it to me

Yes of course ! Thanks for your contribution.

**Comment by kaleemullah786** [comment]
sure. I've difficulty understanding the language, can you help me

**Comment by kaleemullah786** [comment]
**I'm getting this error:**
Module not found: Can't resolve 'public/css/output.css'
> 1 | import styles from "public/css/output.css";
  2 | import highlightStyles from "public/css/highlight.min.css";
  3 | import visualStudioStyles from "public/css/vs2015.min.css";
  4 | import Head from "next/head";

https://nextjs.org/docs/messages/module-not-found

**Comment by amirihusayn** [comment]
> **I'm getting this error:** Module not found: Can't resolve 'public/css/output.css'
> 
> > 1 | import styles from "public/css/output.css";
> > 2 | import highlightStyles from "public/css/highlight.min.css";
> > 3 | import visualStudioStyles from "public/css/vs2015.min.css";
> > 4 | import Head from "next/head";
> 
> https://nextjs.org/docs/messages/module-not-found

Checkout [this](https://github.com/ceituut/ceituut.github.io#we-use-tailwindcss). We ignore generated styles of tailwindcss; So you have to generate it before running project.

**Comment by kaleemullah786** [comment]
Alright. can you help understanding the language

**Comment by amirihusayn** [comment]
> Alright. can you help understanding the language
For example You can checkout [this page](https://codegeeks.ir/requirements/courses/data-structures) that is showing resources for data structure course. At the bottom You see the File explorer that We should work on that.

Okay. Something I forgot to consider is a command to locally generate `tree.json` files that are seed for `FileExplorer.json` component. Give me some time to write the command.

**Comment by amirihusayn** [comment]
Run this commands step by step :  
1- `npm run tailwind-dev`  
2- `npm run clone-collections`  
3- `npm run dev`  

I should say `tree.json` files that are seed for `FileExplorer.json` are generated by **linux tree command** on build process. So to deal with this issue We can temporarily add it by creating a `collections/courses/data-structure/assets/tree.json` with this content :  

```json
[
  {"type":"directory","name":"resources","size":"4.0K","time":"Dec 16 16:24","contents":[
    {"type":"directory","name":"resources/Dr.Tahmoures","size":"4.0K","time":"Dec 16 16:24","contents":[
      {"type":"directory","name":"resources/Dr.Tahmoures/Quiz","size":"4.0K","time":"Dec 16 16:24","contents":[
        {"type":"file","name":"resources/Dr.Tahmoures/Quiz/Final 95.03.29.pdf","size":"118K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Quiz/mid 95.01.28.pdf","size":"106K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Quiz/mid 95.09.03Ans.pdf","size":"1.4M","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Quiz/Quiz1Answers.pdf","size":"887K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Quiz/Quiz2Answers.pdf","size":"396K","time":"Dec 16 16:24"}
    ]},
      {"type":"directory","name":"resources/Dr.Tahmoures/Slides","size":"4.0K","time":"Dec 16 16:24","contents":[
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/01-DS-Intorduction.pdf","size":"1.8M","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/02-AmortizedAnalysis.pdf","size":"353K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/03-Lists.pdf","size":"303K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/04-PreInPostfix.pdf","size":"4.3M","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/07-Tree-.pdf","size":"783K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/08-Tree (AVL--).pdf","size":"200K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/09-Sorting.pdf","size":"500K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/10-Hashing.pdf","size":"339K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/Summation rules.pdf","size":"810K","time":"Dec 16 16:24"}
    ]}
  ]}
  ]}
,
  {"type":"report","directories":3,"files":14}
]
```
Sorry for this tricky process. I should take a look at this later.  

Now if You run the project and navigate to `/requirements/courses/data-structure` You'll see the File Explorer. All to consider is to modify styles related to this component.

**Comment by kaleemullah786** [comment]
clone-collections is spitting this:
collection-update/clone.sh: line 3: $'\r': command not found
collection-update/clone.sh: line 8: $'\r': command not found
collection-update/clone.sh: line 11: $'\r': command not found
collection-update/clone.sh: line 13: syntax error near unexpected token `$'\r''
'ollection-update/clone.sh: line 13: `for (( index=0; index<${contentsLength}; index++));

**Comment by amirihusayn** [comment]
Okay. I think you are on windows. Sorry about this. You can clone only data-structure course with this command :  
`git clone `

**Comment by kaleemullah786** [comment]
it needs to be cloned in main git directory?

**Comment by amirihusayn** [comment]
Yes. It's actually a content resource.

**Comment by kaleemullah786** [comment]
what about this:
Error: ENOENT: no such file or directory, scandir 'D:\open-source-projects\ceituut.github.io\collections\requirements\data\curriculum-guide'

**Comment by kaleemullah786** [comment]
> Yes. It's actually a content resource.

access denied to the repo

**Comment by amirihusayn** [comment]
I think You have to clone all content repositories. Give me a second.

**Comment by amirihusayn** [comment]
Did You try this command inside your git bash?  
`npm run clone-collections`
You have to be inside main path and run it inside git bash. If it doesn't work I'll give you all the clone commands You need to copy and execute.

**Comment by kaleemullah786** [comment]
> Did You try this command inside your git bash? `npm run clone-collections` You have to be inside main path and run it inside git bash. If it doesn't work I'll give you all the clone commands You need to copy and execute.

it does not work

**Comment by amirihusayn** [comment]
Okay. Here You are :  
```
git clone https://github.com/ceituut/challenges collections/challenges
git clone https://github.com/ceituut/events collections/events
git clone https://github.com/ceituut/projects collections/projects
git clone https://github.com/ceituut/blog collections/blog
git clone https://github.com/ceituut/requirements collections/requirements
git clone https://github.com/ceituut/faqs collections/faqs
git clone https://github.com/ceituut/members collections/members
git clone https://github.com/ceituut/companions collections/companions
git clone https://github.com/ceituut/data-structures collections/courses/data-structures
```

**Comment by amirihusayn** [comment]
Could You run the project and see the file explorer? @kaleemullah786

**Comment by kaleemullah786** [comment]
i'm still facing issues

**Comment by amirihusayn** [comment]
> i'm still facing issues

Which one ?

**Comment by kaleemullah786** [comment]
![image](https://github.com/ceituut/ceituut.github.io/assets/108057345/302f7071-be48-4f39-99fa-e4f012f87c42)

**Comment by amirihusayn** [comment]
Did you clone the content repositories? Actually We read those markdown files and generate pages.

**Comment by kaleemullah786** [comment]
I think no, will check soon.

**Comment by amirihusayn** [comment]
> Okay. Here You are :
> 
> ```
> git clone https://github.com/ceituut/challenges collections/challenges
> git clone https://github.com/ceituut/events collections/events
> git clone https://github.com/ceituut/projects collections/projects
> git clone https://github.com/ceituut/blog collections/blog
> git clone https://github.com/ceituut/requirements collections/requirements
> git clone https://github.com/ceituut/faqs collections/faqs
> git clone https://github.com/ceituut/members collections/members
> git clone https://github.com/ceituut/companions collections/companions
> git clone https://github.com/ceituut/data-structures collections/courses/data-structures
> ```

I mean this one

**Comment by kaleemullah786** [comment]
Yeah cloned these but didn't work

**Comment by amirihusayn** [comment]
> ![image](https://user-images.githubusercontent.com/108057345/242939543-302f7071-be48-4f39-99fa-e4f012f87c42.png)

Check the file which this error mentions actually exists in your project.

**Comment by kaleemullah786** [comment]
No, it doesn't

**Comment by amirihusayn** [comment]
> No, it doesn't Bytheway I'm going to sleep, will see tomorrow

So the content repositories didn't clone. Good night !

**Comment by kaleemullah786** [comment]
from where to clone it

> > No, it doesn't Bytheway I'm going to sleep, will see tomorrow
> 
> So the content repositories didn't clone. Good night !

From where to clone this?

**Comment by amirihusayn** [comment]
> > Okay. Here You are :
> > ```
> > git clone https://github.com/ceituut/challenges collections/challenges
> > git clone https://github.com/ceituut/events collections/events
> > git clone https://github.com/ceituut/projects collections/projects
> > git clone https://github.com/ceituut/blog collections/blog
> > git clone https://github.com/ceituut/requirements collections/requirements
> > git clone https://github.com/ceituut/faqs collections/faqs
> > git clone https://github.com/ceituut/members collections/members
> > git clone https://github.com/ceituut/companions collections/companions
> > git clone https://github.com/ceituut/data-structures collections/courses/data-structures
> > ```
> 
> I mean this one

Honestly We didn't use any databases. All the information and contents of this website are get from several github repositories that share markdown and csv files. We call them content repositories and its nessecary to clone them. Does any specific error occur  while running these clone commands?

**Comment by amirihusayn** [comment]
If You don't want to clone the content repositories, just add an empty `README.md` file inside `/collections/courses/data-structures/` directory and a `tree.json` file inside `/collections/courses/data-structures/assets/`. Then In Browser You have to only navigate to `/requirements/courses/data-structures/` path to see the file explorer and update related styles.

**Comment by amirihusayn** [comment]
The `tree.json` file should have this example content :  
```json
[
  {"type":"directory","name":"resources","size":"4.0K","time":"Dec 16 16:24","contents":[
    {"type":"directory","name":"resources/Dr.Tahmoures","size":"4.0K","time":"Dec 16 16:24","contents":[
      {"type":"directory","name":"resources/Dr.Tahmoures/Quiz","size":"4.0K","time":"Dec 16 16:24","contents":[
        {"type":"file","name":"resources/Dr.Tahmoures/Quiz/Final 95.03.29.pdf","size":"118K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Quiz/mid 95.01.28.pdf","size":"106K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Quiz/mid 95.09.03Ans.pdf","size":"1.4M","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Quiz/Quiz1Answers.pdf","size":"887K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Quiz/Quiz2Answers.pdf","size":"396K","time":"Dec 16 16:24"}
    ]},
      {"type":"directory","name":"resources/Dr.Tahmoures/Slides","size":"4.0K","time":"Dec 16 16:24","contents":[
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/01-DS-Intorduction.pdf","size":"1.8M","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/02-AmortizedAnalysis.pdf","size":"353K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/03-Lists.pdf","size":"303K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/04-PreInPostfix.pdf","size":"4.3M","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/07-Tree-.pdf","size":"783K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/08-Tree (AVL--).pdf","size":"200K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/09-Sorting.pdf","size":"500K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/10-Hashing.pdf","size":"339K","time":"Dec 16 16:24"},
        {"type":"file","name":"resources/Dr.Tahmoures/Slides/Summation rules.pdf","size":"810K","time":"Dec 16 16:24"}
    ]}
  ]}
  ]}
,
  {"type":"report","directories":3,"files":14}
]
```

**Comment by kaleemullah786** [comment]
> If You don't want to clone the content repositories, just add an empty `README.md` file inside `/collections/courses/data-structures/` directory and a `tree.json` file inside `/collections/courses/data-structures/assets/`. Then In Browser You have to only navigate to `/requirements/courses/data-structures/` path to see the file explorer and update related styles.

this works! thanks
